name: Build Main Branch and Publish Maven Artifact

on:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up secrets
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_FILE }}" | base64 --decode > ./test.json
        working-directory: ./cert

      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>github</id><username>${{ github.actor }}</username><password>${{ secrets.GH_PACKAGES_TOKEN}}</password></server></servers></settings>" > ~/.m2/settings.xml

      - name: Build with Maven
        run: mvn -B clean install --file pom.xml
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ../cert/test.json
          PROJECT_ID: test-cmile-project

      - name: Publish package
        run: mvn --batch-mode deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN}}

      - name: Publish Versioned Package
        run: |
          mvn versions:set -DnewVersion=1.0.0-Build-${{ github.run_number }}
          mvn -B deploy -DskipTests
